[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Erik Sandrén <erik.sandren@dataton.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[[bin]]
name = "day1"
path = "src/day1.rs"
